security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: in_memory
            webauthn:
                registration:
                    enabled: true
                    profile: default
                    routes:
                        options_path: '/attestation/options'
                        result_path: '/attestation/result'
                authentication:
                    enabled: true
                    profile: default
                    routes:
                        options_path: '/assertion/options'
                        result_path: '/assertion/result'
        monitor:
            pattern: ^/(info|health)$
            security: false
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    - { path: ^/attestation/options, roles: PUBLIC_ACCESS, requires_channel: 'https' }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
