services:
    _defaults:
        autowire: true
        autoconfigure: true

    sensiolabs.security_checker:
        synthetic: true

    sensiolabs.security_checker_command:
        synthetic: true
