FROM ghcr.io/openconext/openconext-basecontainers/php82-apache2:latest
# Set the default workdir
WORKDIR /var/www/html
ADD output.zip /var/www/html/
# Add the application configuration files
RUN cp .env.dist .env
RUN cp config/openconext/parameters.yaml.dist config/openconext/parameters.yaml
# Add the config files for Apache2
RUN rm -rf /etc/apache2/sites-enabled/*
COPY ./docker/conf/webauthn-apache2.conf /etc/apache2/sites-enabled/webauthn.conf
RUN rm -rf /var/www/html/var/cache/prod && \
  mkdir -p /var/www/html/var/ && \
  chown -R www-data /var/www/html/var
EXPOSE 80

CMD ["apache2-foreground"]
