gssp_saml:
    resource: '@SurfnetGsspBundle/Resources/config/routing.yml'
    type: attribute

openconext_monitor:
    resource:   "@OpenConextMonitorBundle/Resources/config/routing.yml"
    prefix:     /
