parameters:
    locale: nl_NL
    database_url: sqlite:///%kernel.project_dir%/var/webauthn.db

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $logger: '@surfnet_gssp.logger'
            $stateHandler: '@surfnet_gssp.state_handler.service'
            $supportUrl: '%support_url%'
            $supportEmail: '%support_email%'
            $locales: '%locales%'
            $userDisplayName: '%user_display_name%'
            $trustedCertificatesDirectory: '%trusted_certificates_directory%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Dev\:
        resource: '../dev/*'
        exclude: '../dev/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Dev\Controller\:
        resource: '../dev/Controller'
        tags: ['controller.service_arguments']


    Surfnet\Webauthn\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    Surfnet\Webauthn\Repository\:
        resource: '../src/Repository/*'

    Surfnet\Webauthn\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Surfnet\GsspBundle\Service\ValueStore\SessionValueStore:
        alias: surfnet_gssp.value_store.service

    Surfnet\Webauthn\Service\InMemoryAttestationCertificateTrustStore:
        arguments:
            - '$trustedCertificates': []

    Surfnet\Webauthn\Service\AttestationCertificateTrustStore:
        factory: '@Surfnet\Webauthn\Service\AttestationCertificateTrustStoreFactory'
