parameters:
    locale: nl_NL

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $logger: '@surfnet_gssp.logger'
            $stateHandler: '@surfnet_gssp.state_handler.service'
            $supportUrl: '%support_url%'
            $supportEmail: '%support_email%'
            $locales: '%locales%'
            $userDisplayName: '%user_display_name%'
            $jwtMdsBlobFileName: '%fido2_jwt_mds_blob_file_name%'
            $jwtMdsRootCertFileName: '%fido2_jwt_mds_root_certificate_file_name%'
            $mdsCacheDir: '%fido2_mds_cache_dir%'

    Surfnet\Webauthn\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    Surfnet\Webauthn\Repository\:
        resource: '../src/Repository/*'

    Surfnet\Webauthn\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Surfnet\GsspBundle\Service\ValueStore\SessionValueStore:
        alias: surfnet_gssp.value_store.service

    Webauthn\Bundle\Repository\CanRegisterUserEntity:
        alias: Surfnet\Webauthn\Repository\UserRepository
