name: Run QA tests (static analysis, lint and unit tests)
on: [pull_request]

jobs:
  run-qa-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Init environment
        run: cd ci/docker && ./init.sh

      - name: Build frontend assets
        run: yarn && yarn encore production

      - name: Run QA tests
        run: |
            cd ci/docker && docker compose exec -T webauthn bash -c 'composer check'