name: Test
on:
  push:
    branches:    
      - '**'        # matches every branch
jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Copy config
          run: |
            cp .env.ci .env
            cp config/packages/parameters.yml.dist config/packages/parameters.yml
        - uses: actions/cache@v2
          id: cache-db
          with:
            path: ~/.symfony/cache
            key: db
        - uses: symfonycorp/security-checker-action@v2
        - name: Yarn Audit
          uses: pragatheeswarans/yarn-audit-action@v1.0.0
          with:
              token: ${{ secrets.GITHUB_TOKEN }}
              label: 'yarn-issue'
        - name: Install PHP
          uses: "shivammathur/setup-php@v2"
          with:
            php-version: "7.2"
        - name: Composer install
          uses: php-actions/composer@v6
          with:
            php_version: "7.2"
            php_extensions: gmp
            version: 1
            command: install
        - name: Yarn install
          run: |
            yarn install
        - name: Composer test
          uses: php-actions/composer@v6
          with:
            php_version: "7.2"
            php_extensions: gmp
            version: 1
            command: test
        - name: Yarn install and tests
          run: |
            yarn install
            yarn jest
            yarn tslint --project tsconfig.json
            yarn tsc --noEmit
        - name: PHP Code Style (phpcs)
          uses: chindit/actions-phpcs@master
          with:
            dir: src/
        - name: Composer test
          uses: php-actions/composer@v6
          with:
            php_version: "7.2"
            version: 1
            command: test
